version: '3.8'

services:
    php:
        # note you need to manually build this image from base dockerfile above FIRST!
        image: jokes-cms/base-php-nginx
        container_name: php
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        volumes:
            # used delegated mode here on docker for mac for faster disk I/O
            - ./app:/var/www/app:delegated
            - ./app/package.json:/var/www/package.json
            - ./app/package-lock.json:/var/www/package-lock.json
            - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx-site.conf:/etc/nginx/conf.d/default.conf
              # mount in dev certs if you want to dev over ssl
              #- ./dev-cert.crt:/etc/nginx/ssl/cert.crt
              #- ./dev-key.pem:/etc/nginx/ssl/key.pem
            - notused:/var/www/app/node_modules
        #entrypoint: /usr/local/bin/docker-php-entrypoint-dev
        command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
        ports:
            - "8080:80"
            - "8443:443"
            - "9001:9001"
        depends_on:
            - mysql
        stdin_open: true
        tty: true
        environment:
            CHOKIDAR_USEPOLLING: "true"
            APP_NAME: jokes-cms
            APP_ENV: local
            APP_DEBUG: "true"
            APP_KEY: KEYGOESHERE
            APP_LOG: errorlog
            APP_URL: "http://localhost"
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: jokes-cms

    mysql:
        image: mysql:5.7
        container_name: mysql
        volumes:
            - mysql:/var/lib/mysql
        ports:
            # we only expose this port in local dev for using mysql tools/guis on your host
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-jokes-cms}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            
# using this named volume ensures db's hang around between "up's"
volumes:
    mysql:
    notused:

